/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aplikasissilap;

import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.File;
import java.io.FileOutputStream;
import java.awt.Desktop;
/**
 *
 * @author LENOVO
 */
public class DataBantuanAdmin extends javax.swing.JFrame {
    
    Koneksi k = new Koneksi();
    private java.sql.PreparedStatement stat;
    private java.sql.ResultSet rs;
    private int selectedId = -1; // Untuk update & delete

    /**
     * Creates new form DataBencana
     */
    public DataBantuanAdmin() {
        initComponents();
        k.connect();
        refreshTable();
        tb_bantuan.getSelectionModel().addListSelectionListener(e -> pilihData());
        
        bt_input.addActionListener(evt -> bt_inputActionPerformed(evt));
        bt_delete.addActionListener(evt -> bt_deleteActionPerformed(evt));
        bt_cetak.addActionListener(evt -> bt_cetakActionPerformed(evt));
        bt_logout.addActionListener(evt -> bt_logoutActionPerformed(evt));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_jumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_deskripsi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_tanggaldisalurkan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_namabantuan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_bantuan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        bt_cetak = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();
        bt_input = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_logout = new javax.swing.JButton();
        bt_verif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA BANTUAN");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Jumlah");

        tf_jumlah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Deskripsi");

        tf_deskripsi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Tanggal Disalurkan");

        tf_tanggaldisalurkan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Nama Bantuan");

        tf_namabantuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tb_bantuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_bantuan);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bt_cetak.setBackground(new java.awt.Color(204, 204, 204));
        bt_cetak.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        bt_cetak.setText("CETAK LAPORAN");
        bt_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cetakActionPerformed(evt);
            }
        });

        bt_update.setBackground(new java.awt.Color(204, 204, 204));
        bt_update.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        bt_update.setText("UPDATE");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });

        bt_input.setBackground(new java.awt.Color(204, 204, 204));
        bt_input.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        bt_input.setText("INPUT");
        bt_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inputActionPerformed(evt);
            }
        });

        bt_delete.setBackground(new java.awt.Color(204, 204, 204));
        bt_delete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        bt_delete.setText("DELETE");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_update, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cetak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_update, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(bt_cetak, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(bt_input, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(bt_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_logout.setText("LOGOUT");

        bt_verif.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_verif.setText("VERIFIKASI LAPORAN");
        bt_verif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_verif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_namabantuan, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(tf_jumlah)
                            .addComponent(tf_deskripsi)
                            .addComponent(tf_tanggaldisalurkan)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_verif, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_namabantuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_tanggaldisalurkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTable() {
        try {
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Nama Bantuan");
            model.addColumn("Jumlah");
            model.addColumn("Deskripsi");
            model.addColumn("Tanggal");

            stat = k.getCon().prepareStatement("SELECT * FROM bantuan");
            rs = stat.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("nama_bantuan"),
                    rs.getInt("jumlah"),
                    rs.getString("deskripsi"),
                    rs.getString("tanggal_disalurkan")
                });
            }
            tb_bantuan.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error loading table: " + e.getMessage());
        }
    }

    private void pilihData() {
        int row = tb_bantuan.getSelectedRow();
        if (row != -1) {
            selectedId = Integer.parseInt(tb_bantuan.getValueAt(row, 0).toString());
            tf_namabantuan.setText(tb_bantuan.getValueAt(row, 1).toString());
            tf_jumlah.setText(tb_bantuan.getValueAt(row, 2).toString());
            tf_deskripsi.setText(tb_bantuan.getValueAt(row, 3).toString());
            tf_tanggaldisalurkan.setText(tb_bantuan.getValueAt(row, 4).toString());
        }
    }
    
    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        // TODO add your handling code here:
        if (selectedId == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data dulu");
            return;
        }
        try {
            stat = k.getCon().prepareStatement("UPDATE bantuan SET nama_bantuan=?, jumlah=?, deskripsi=?, tanggal_disalurkan=? WHERE id=?");
            stat.setString(1, tf_namabantuan.getText());
            stat.setInt(2, Integer.parseInt(tf_jumlah.getText()));
            stat.setString(3, tf_deskripsi.getText());
            stat.setString(4, tf_tanggaldisalurkan.getText());
            stat.setInt(5, selectedId);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error update: " + e.getMessage());
        }
    }//GEN-LAST:event_bt_updateActionPerformed

    private void bt_verifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verifActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new VerifiksasiAdmin().setVisible(true); 
    }//GEN-LAST:event_bt_verifActionPerformed

    private void bt_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inputActionPerformed
        // TODO add your handling code here:
        try {
            stat = k.getCon().prepareStatement("INSERT INTO bantuan (nama_bantuan, jumlah, deskripsi, tanggal_disalurkan) VALUES (?, ?, ?, ?)");
            stat.setString(1, tf_namabantuan.getText());
            stat.setInt(2, Integer.parseInt(tf_jumlah.getText()));
            stat.setString(3, tf_deskripsi.getText());
            stat.setString(4, tf_tanggaldisalurkan.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error input: " + e.getMessage());
        }
    }//GEN-LAST:event_bt_inputActionPerformed

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        // TODO add your handling code here:
        if (selectedId == -1) {
                    JOptionPane.showMessageDialog(null, "Pilih data dulu");
                    return;
                }
                try {
                    stat = k.getCon().prepareStatement("DELETE FROM bantuan WHERE id=?");
                    stat.setInt(1, selectedId);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                    refreshTable();
                    selectedId = -1;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error delete: " + e.getMessage());
                }
            }
    
            private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {
                new Login().setVisible(true);
                this.dispose();
    }//GEN-LAST:event_bt_deleteActionPerformed

    private void bt_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cetakActionPerformed
        // TODO add your handling code here:
        try {
            String path = "laporan_bantuan.pdf";
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(path));
            document.open();

            Font fontJudul = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
            Paragraph judul = new Paragraph("Laporan Data Bantuan", fontJudul);
            judul.setAlignment(Element.ALIGN_CENTER);
            document.add(judul);
            document.add(new Paragraph(" ")); // spasi

            PdfPTable pdfTable = new PdfPTable(tb_bantuan.getColumnCount());

            for (int i = 0; i < tb_bantuan.getColumnCount(); i++) {
                pdfTable.addCell(new PdfPCell(new Phrase(tb_bantuan.getColumnName(i))));
            }

            for (int rows = 0; rows < tb_bantuan.getRowCount(); rows++) {
                for (int cols = 0; cols < tb_bantuan.getColumnCount(); cols++) {
                    Object value = tb_bantuan.getValueAt(rows, cols);
                    pdfTable.addCell(value != null ? value.toString() : "");
                }
            }

            document.add(pdfTable);
            document.close();

            JOptionPane.showMessageDialog(this, "Laporan berhasil dicetak ke: " + path);
            Desktop.getDesktop().open(new File(path)); // buka PDF langsung

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak: " + e.getMessage());
        }
    }//GEN-LAST:event_bt_cetakActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBantuanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBantuanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBantuanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBantuanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBantuanAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt_cetak;
    public javax.swing.JButton bt_delete;
    public javax.swing.JButton bt_input;
    public javax.swing.JButton bt_logout;
    public javax.swing.JButton bt_update;
    public javax.swing.JButton bt_verif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_bantuan;
    private javax.swing.JTextField tf_deskripsi;
    private javax.swing.JTextField tf_jumlah;
    private javax.swing.JTextField tf_namabantuan;
    private javax.swing.JTextField tf_tanggaldisalurkan;
    // End of variables declaration//GEN-END:variables
}
